[build]
  command = "yarn generate"
  functions = "functions"
  publish = "dist"

# https://github.com/cypress-io/netlify-plugin-cypress
# test the site after deploy

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"
  # runs Cypress tests against the deployed URL
  [plugins.inputs]
    record = true
  # run Cypress tests before building and deploying
  [plugins.inputs.preBuild]
    enable = true
    # call the same commands as we do locally
    start = 'nuxt'
    wait-on = 'http://localhost:3000'
